swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
    <svg/onload=alert()>
  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /accounts:
    get:
      summary: "Account information"
      description: "Returns account details."
      responses:
        '200':
          description: "Successful retrieval of account information"
          schema:
            type: object
